config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :words do
  	collection {post :import}
  end
  root 'words#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/definition.rb
class Definition < ApplicationRecord
	validates :text, :presence => true, :uniqueness => true
	has_many :word_definitions
	has_many :words, through: :word_definitions

end

app/models/word.rb
require 'csv'
class Word < ApplicationRecord
	validates :name, :uniqueness => true, :presence => true
	validates_length_of :name, :within => 2..100
	validates_format_of :name, with: /[^\s]+/i

	has_many :word_definitions
	has_many :definitions, through: :word_definitions
	accepts_nested_attributes_for :definitions

	def self.import(file, name_header, definition_header)
		log = {:word_errors => {}}
		if file.path.end_with?('.csv')
			begin
				log[:words_imported] = 0
				log[:words_updated] = 0
				log[:words_created] = 0
				file_parameters = {:headers => true, :row_sep => :auto, :encoding => 'ISO-8859-1', skip_blanks: true, skip_lines: /[\n\r]+/}
				log[:word_total] = CSV.read(file.path, file_parameters).length rescue 0
				CSV.foreach(file.path, file_parameters) do |row|
					word = Word.find_by_name(row[name_header])
					if word.present?
						word.update(definitions_attributes: [text: row[definition_header]])
						log[:words_updated] += 1
					else
						word = Word.new(name: row[name_header], definitions_attributes: [text: row[definition_header]])
						log[:words_created] += 1
					end
					word.set_unique_definitions
					if word.save
						log[:words_imported] += 1
					else
						log[:word_errors][row[name_header]] = word.errors.full_messages
					end
				end
			rescue CSV::MalformedCSVError => csv_error
				log[:file_error] = csv_error.message
				raise csv_error, log.to_s, csv_error.backtrace
			end
		elsif file.path.end_with? '.xml'
			#code for importing xml data
		else
			log[:file_error] = 'File type not supported'
		end
		log
	end

	def definition
		return '' if definitions.blank?
		definitions.first.text
	end

	def synonyms
		synonyms = []
		definitions.each do |definition_object|
			synonym_words = Word.select{|word| word.definitions.include?(definition_object)}
			synonym_words.each do |synonym|
				synonyms << synonym.name
			end
		end
		synonyms.delete(name)
		synonyms
	end

	def set_unique_definitions
		unique_definitions = []
    	definitions.each do |original_definition|
      		matching_definition = Definition.find_by_text(original_definition.text)
      		if matching_definition.present?
        		unique_definitions << matching_definition
      		else
        		unique_definitions << original_definition
      		end
      	end
      	self.definitions = unique_definitions.uniq
	end

	def self.search(term)
	  if term
	    where('name LIKE ?', "%#{term}%")
	  else
	    all
	  end
	end

end

app/models/word_definition.rb
class WordDefinition < ApplicationRecord
	belongs_to :word
    belongs_to :definition
    validates_presence_of :word
    validates_presence_of :definition
    accepts_nested_attributes_for :definition

    def text
    	definition.text
    end

    def name
    	word.name
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  	render(:status => 404)
  end

  def internal_server_error
  	render(:status => 500)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.search(params[:term]).sort_by{|word| word.name}
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])
  end

  def import
    if params[:file].present?
      notice = 'CSV data was successfully uploaded.'
      begin
        log = Word.import(params[:file], params[:name_header], params[:definition_header])
      rescue Exception => error
        if error.message.match?(/\{.+\}/).present?
          log = eval error.message
        else
          log = {file_error: error.message}
        end
      end
      if log[:file_error].present?
        notice = ' Error processing file: ' + log[:file_error]
      end
      notice += "<br>" + log[:words_imported].to_s + " out of " + log[:word_total].to_s + " words imported" if log[:words_imported].present?
      notice += "<br>" + log[:words_updated].to_s + " words updated" if log[:words_updated].present?
      notice += "<br>" + log[:words_created].to_s + " words created" if log[:words_created].present?
      if log[:word_errors].present?
        notice += "<br> Word errors: <ul>" + log[:word_errors].keys.map{|name| '<li>' + name + ': ' + log[:word_errors][name].join + '</li>'}.join + '</ul>'
      end
      respond_to do |format|
        format.html { redirect_to words_url, notice: notice}
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to words_url, notice: 'CSV file not selected' }
        format.json { head :no_content }
      end
    end
  end

  # GET /words/new
  def new
    @word = Word.new
    @word_definition = @word.word_definitions.build
    @definitions = [@word_definition.build_definition]
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
    @definitions = @word.definitions
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.find_by_name(word_params[:name])
    if @word.present?
      @word.update(definitions_attributes: word_params[:definitions_attributes])
    else
      @word = Word.new(word_params)
    end
    @word.set_unique_definitions

    respond_to do |format|
      if @word.save

        format.html { redirect_to @word, notice: 'Word was successfully created.'}
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    #defines parameters for word and definition models
    def word_params
      params.require(:word).permit(:name, 
        definitions_attributes: [:id, :text]
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyDictionary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :word %><br>
    <%= form.text_field :name %>
  </p>
 
  <ol>
    <%= form.fields_for :definitions, definitions do |definition_form| %>
          <li>
            <p>
              <%= definition_form.label :definition %>
              <%= definition_form.text_field :text %>
            </p>
          </li>
        <% end %>
  </ol>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word , definitions: @definitions %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<%= form_tag(words_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', term: nil  %>
<% end %>

<p id="notice"><%= notice.html_safe if notice.present? %></p>

<h1>Dictionary</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Definition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= word.definition %></td>
        <td><%= link_to 'Details', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

<br>

<h3>Import CSV</h3>
<%= form_tag(import_words_path, multipart: :true) do %>
  <%= file_field_tag :file %>
  <%= label_tag :name_header, 'name header' %>
  <%= text_field_tag :name_header, 'name' %>
  <%= label_tag :definition_header, 'definition header' %>
  <%= text_field_tag :definition_header, 'definition' %>
  <%= submit_tag 'Import' %>
<% end %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word , definitions: @definitions %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.name %>
</p>
 
<p>
  <strong>Definitions:</strong>
  <ol>
  	<% @word.definitions.each do |definition| %>
  		<li>
  			<%= definition.text %>
  		</li>
  	<% end %>
  </ol>
</p>

<p>
  <strong>Synonyms:</strong>
  <ul>
    <% @word.synonyms.each do |synonym| %>
      <li>
        <%= synonym %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>